---
layout: default
priority: 0.5
title: Basic information about CDI TCK (Technology Compatibility Kit)
desc: Basic information about CDI TCK (Technology Compatibility Kit)
change_frequency: weekly
---

== CDI TCK

Our https://en.wikipedia.org/wiki/Technology_Compatibility_Kit[TCK^] is open as well and contributions are more than welcome. Important information:

* Source code at https://github.com/eclipse-ee4j/cdi[GitHub^]
* Issue tracker in https://github.com/eclipse-ee4j/cdi/issues[GitHub Issues^]
* Distribution bundles are available at https://download.eclipse.org/jakartaee/cdi/[download.eclipse.org/jakartaee/cdi^]
* Mailing list: cdi-dev@eclipse.org

You can check the connection between specification and TCK by looking at link:$$https://docs.jboss.org/cdi/spec/2.0.EDR1/cdi-spec-with-assertions.html$$[specification with TCK assertions] where each chapter starts with a list of TCK assertions with links to TCK tests for given chapter.

Documentation is found in the doc directory of the TCK distribution zip.

=== How to execute your updated or new TCK test

1. Build TCK with your update by running:
[source]
mvn clean install
2. Get the jboss-tck-runner. Either you can use the one available in CDI TCK distribution bundle or you can use the same one from https://github.com/weld/core[Weld source code repository^]
3. From jboss-tck-runner execute following command and provide your TCK version (also be aware of Weld version you are running):
[source]
mvn clean test -Dtest=<your_test_name> -Dcdi.tck.version=<cdi_tck_version>
4. Execution in previous step is run at Arquillian Weld embedded container. If you need to execute by using real container then please check documentation link above.