---
title: "CDI EG meeting 12/16/2013 notes on CDI 1.2"
summary: Conclusion on CDI 1.2 preparation. Decision for pending issue. Adding last issues...
layout: post
authors: [asd]
tags: [meeting]
priority: 1
change_frequency: daily
---


The following people assisted this meeting :

* Mark Struberg (ms)
* Joseph Bergmark(jb)
* Jozef Hartinger (jh)
* Martin Kouba (mk)
* JJ Snyder (jj)
* Phil Zampino (pz)
* Antoine Sabot-Durand (asd)

== Proposed Agenda 

The following agenda was proposed

1. Discussion on the last ticket pending : CDI-395 Public fields in extensions should not be allowed
2. Last second ticket
3. Next step for the MR.

==  Discussion on CDI-395

We were waiting on implementation feedback on this point. *jh* told us that there was too much risk to create retro-compatibility issues. So it was decided to remove CDI-395 from MR.


== Last minute issues



[cols="1,6,1,4",options="header"]
|===
|Jira|Description|Decision|Note
|https://issues.jboss.org/browse/CDI-408[CDI-408^]|bean-discovery-mode="annotated" and Producers/Observers in @Dependent beans|in MR|
|https://issues.jboss.org/browse/CDI-410[CDI-410^]|@RequestScoped Javadoc outdated|in MR|
|https://issues.jboss.org/browse/CDI-388[CDI-388^]|Session bean specialization example is not valid|in MR|
|https://issues.jboss.org/browse/CDI-376[CDI-376^]|BeanManager#getProducerFactory return type differs between API and spec|in MR|
|https://issues.jboss.org/browse/CDI-411[CDI-411^]|CDI conversation activation conflicts with the Servlet spec|Pending|needs some test before decicing if we can include it in MR. Test leaded by *jh*
|===


== Next Step

The list is now closed (except for 411) It's accessible link:../CDI-1-2-issues-list[here] and in http://s.shr.lc/1dL7BrF[Jira].
The Maintenance Release will be officially launch on the 6th january week. By then, work and discussion can start on the ticket chosen for this MR.  
