=== CDI 2.0 Hot news

You'll find all CDI 2.0 EG meeting log and minutes http://transcripts.jboss.org/meeting/irc.freenode.org/cdi-dev/index.html[here^]

_(updated on February 2nd)_

The Asynchronous events and Java SE support features are current hot topic.

After a lot of discussion in workshop doc and IRC discussion, both features came to Jira ticket for more structured discussion

* https://issues.jboss.org/browse/CDI-26?focusedCommentId=13034063&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13034063[Java SE Bootstrap^]
* https://issues.jboss.org/browse/CDI-499[Asynchronous events^]


=== Contribution

Contribution to CDI 2.0 is open to all (no need to be part of the Expert Group or the JCP). If you want to contribute, the best place to start is to read our link:/news/2014/08/26/CDI-20_needs_you/[blog post] on the subject.

=== Work status

Work on CDI 2.0 is based on different workshops as explained  link:/news/2014/10/06/CDI-20_working_method/[here^].
The table below give to resource to different workshop. It will be updated


[width="100%",cols="15,15,25,45",options="header"]
|===

|Workshop|Status |Doc link|Description

|Parts|not started|http://bit.ly/cdi2wsprt|working on modularity (sub specs)

|Events|started|http://bit.ly/cdi2wsevt|enhance events (asynchronous, ordering,etc...)

|AOP|started|http://bit.ly/cdi2wsaop|Interceptors & Decoractors enhancement

|Java SE|Jira ticke|http://bit.ly/cdi2wsjse|Boostrap CDI in Java SE

|JDK 8 |started|http://bit.ly/cdi2wsjk8|enhancement from JDK 8

|SPI |not started|http://bit.ly/cdi2wsspi|more open SPI for 3rd party

|Contexts |not started|http://bit.ly/cdi2wsctx|provide a way to start/stop contexts for SE mode


|===
