=== Hot news

_(updated on October 23rd)_

Our last IRC meeting (Oct 22nd) was focused on events. http://bit.ly/cdi2wsevt[The workshop document^] contains a lot of leads on ordering and asynchronous events.
If you missed the debate, you can retrieve it http://transcripts.jboss.org/meeting/irc.freenode.org/cdi-dev/2014/cdi-dev.2014-10-22-16.00.log.html[here^] or if you prefere the short version the minutes of the meeting are  http://transcripts.jboss.org/meeting/irc.freenode.org/cdi-dev/2014/cdi-dev.2014-10-22-16.00.html[there^]

Last week (oct 15th-16th) we had our Face to Face meeting, check our feedback link:/news/2014/10/20/CDI-2_0-first-face-to-face-meeting-feedback/[here].

=== Contribution

Contribution to CDI 2.0 is open to all (no need to be part of the Expert Group or the JCP). If you want to contribute, the best place to start is to read our link:/news/2014/08/26/CDI-20_needs_you/[blog post] on the subject.

=== Work status

Work on CDI 2.0 is based on different workshops as explained  link:/news/2014/10/06/CDI-20_working_method/[here^].
The table below give to resource to different workshop. It will be updated


[width="100%",cols="15,15,25,45",options="header"]
|===

|Workshop|Status |Doc link|Description

|Parts|not started|http://bit.ly/cdi2wsprt|working on modularity (sub specs)

|Events|started|http://bit.ly/cdi2wsevt|enhance events (asynchronous, ordering,etc...)

|AOP|started|http://bit.ly/cdi2wsaop|Interceptors & Decoractors enhancement

|Java SE|not started|http://bit.ly/cdi2wsjse|Boostrap CDI in Java SE

|JDK 8 |started|http://bit.ly/cdi2wsjk8|enhancement from JDK 8

|SPI |not started|http://bit.ly/cdi2wsspi|more open SPI for 3rd party

|Contexts |not started|http://bit.ly/cdi2wsctx|go beyond the the thread-bound request-response model used by context today


|===
