=== Hot news

_(updated on October 9th)_

Check our last (October 8th) IRC meeting
 http://transcripts.jboss.org/meeting/irc.freenode.org/cdi-dev/2014/cdi-dev.2014-10-08-16.00.html[minutes^] which was focused on Java One feedback, Face to Face meetings and started workshops.

Next IRC meeting on October 22nd will be focused on Event enhancement. If you want to participate please take a moment to read the http://bit.ly/cdi2wsevt[Event workshop document] and join the discussion to prepare the meeting.

=== Contribution

Contribution to CDI 2.0 is open to all (no need to be part of the Expert Group or the JCP). If you want to contribute, the best place to start is to read our link:/news/2014/08/26/CDI-20_needs_you/[blog post] on the subject.

=== Work status

Work on CDI 2.0 is based on different workshops as explained  link:/news/2014/10/06/CDI-20_working_method/[here^].
The table below give to resource to different workshop. It will be updated


[width="100%",cols="15,15,25,45",options="header"]
|===

|Workshop|Status |Doc link|Description

|Parts|not started|http://bit.ly/cdi2wsprt|working on modularity (sub specs)

|Events|started|http://bit.ly/cdi2wsevt|enhance events (asynchronous, ordering,etc...)

|AOP|started|http://bit.ly/cdi2wsaop|Interceptors & Decoractors enhancement

|Java SE|not started|http://bit.ly/cdi2wsjse|Boostrap CDI in Java SE

|JDK 8 |started|http://bit.ly/cdi2wsjk8|enhancement from JDK 8

|SPI |not started|http://bit.ly/cdi2wsspi|more open SPI for 3rd party

|Contexts |not started|http://bit.ly/cdi2wsctx|go beyond the the thread-bound request-response model used by context today


|===
